/**
 * Attribution for the category cover photographs.
 *
 * Generated by `pnpm covers:fetch`. Anything that is not CC0 or public
 * domain must carry its credit wherever the image appears — that is the
 * condition the licence is granted under, not a nicety.
 */

export interface CoverCredit {
  title: string
  licence: string
  artist: string
  source: string
}

export const COVER_CREDITS: Record<string, CoverCredit> = {
  "restorani": {
    "title": "File:Interior dining room of a LongHorn Steakhouse restaurant in Blairsville, Georgia 02.jpg",
    "licence": "CC BY 4.0",
    "artist": "Harrison Keely",
    "source": "https://commons.wikimedia.org/wiki/File%3AInterior%20dining%20room%20of%20a%20LongHorn%20Steakhouse%20restaurant%20in%20Blairsville%2C%20Georgia%2002.jpg"
  },
  "kafulinja": {
    "title": "File:Coffee shop 2 - Wellington, New Zealand.jpg",
    "licence": "CC0",
    "artist": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File%3ACoffee%20shop%202%20-%20Wellington%2C%20New%20Zealand.jpg"
  },
  "brza-hrana": {
    "title": "File:Avocado bacon cheeseburger and pineapple smoothie.jpg",
    "licence": "Public domain",
    "artist": "Photographer: Kyle T. Ramirez",
    "source": "https://commons.wikimedia.org/wiki/File%3AAvocado%20bacon%20cheeseburger%20and%20pineapple%20smoothie.jpg"
  },
  "picerii": {
    "title": "File:Commercial Wood Fired Pizza Ovens.jpg",
    "licence": "CC BY-SA 4.0",
    "artist": "Sahiludiawar",
    "source": "https://commons.wikimedia.org/wiki/File%3ACommercial%20Wood%20Fired%20Pizza%20Ovens.jpg"
  },
  "stomatolozi": {
    "title": "File:Guantanamo captive dental clinic -c.jpg",
    "licence": "Public domain",
    "artist": "DoD",
    "source": "https://commons.wikimedia.org/wiki/File%3AGuantanamo%20captive%20dental%20clinic%20-c.jpg"
  },
  "avtoservisi": {
    "title": "File:Rootes Maidstone building.jpg",
    "licence": "CC0",
    "artist": "John K Thorne",
    "source": "https://commons.wikimedia.org/wiki/File%3ARootes%20Maidstone%20building.jpg"
  },
  "majstori": {
    "title": "File:Edwin Smith Papyrus v2.jpg",
    "licence": "Public domain",
    "artist": "Jeff Dahl",
    "source": "https://commons.wikimedia.org/wiki/File%3AEdwin%20Smith%20Papyrus%20v2.jpg"
  },
  "saloni-za-ubavina": {
    "title": "File:Hair salon - Arlington, MA.jpg",
    "licence": "CC0",
    "artist": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File%3AHair%20salon%20-%20Arlington%2C%20MA.jpg"
  },
  "nedvizhnini": {
    "title": "File:Apartment building near the Duomo in Milan.jpg",
    "licence": "CC BY 4.0",
    "artist": "sagesolar",
    "source": "https://commons.wikimedia.org/wiki/File%3AApartment%20building%20near%20the%20Duomo%20in%20Milan.jpg"
  },
  "smestuvanje": {
    "title": "File:Michael Ancher - Spisestuen i Brøndums Hotel ved lampelys.png",
    "licence": "Public domain",
    "artist": "Michael Ancher",
    "source": "https://commons.wikimedia.org/wiki/File%3AMichael%20Ancher%20-%20Spisestuen%20i%20Br%C3%B8ndums%20Hotel%20ved%20lampelys.png"
  },
  "svadbi-i-nastani": {
    "title": "File:Pierre Courteys - The Wedding Banquet of Cupid and Psyche - Walters 44210.jpg",
    "licence": "Public domain",
    "artist": "Pierre Courteys",
    "source": "https://commons.wikimedia.org/wiki/File%3APierre%20Courteys%20-%20The%20Wedding%20Banquet%20of%20Cupid%20and%20Psyche%20-%20Walters%2044210.jpg"
  },
  "advokati-i-smetkovodstvo": {
    "title": "File:Books, pencils, laptop, and iphone on a desk (Unsplash).jpg",
    "licence": "CC0",
    "artist": "Aleks Dorohovich aleksdorohovich",
    "source": "https://commons.wikimedia.org/wiki/File%3ABooks%2C%20pencils%2C%20laptop%2C%20and%20iphone%20on%20a%20desk%20(Unsplash).jpg"
  },
  "prodavnici": {
    "title": "File:Amazon Go Grocery - 610 Pike Street, Seattle - interior with carts and shelves.jpg",
    "licence": "CC BY-SA 4.0",
    "artist": "SounderBruce",
    "source": "https://commons.wikimedia.org/wiki/File%3AAmazon%20Go%20Grocery%20-%20610%20Pike%20Street%2C%20Seattle%20-%20interior%20with%20carts%20and%20shelves.jpg"
  }
}

const NO_ATTRIBUTION = ['CC0', 'Public domain']

export function hasCover(slug: string): boolean {
  return slug in COVER_CREDITS
}

/** Null when the licence does not require a credit line. */
export function coverCredit(slug: string): string | null {
  const c = COVER_CREDITS[slug]
  if (!c || NO_ATTRIBUTION.includes(c.licence)) return null
  const who = c.artist || 'Wikimedia Commons'
  return `${who} · ${c.licence}`
}
